networks:
  url-shorter:

services:
  application:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SHORTER_BASE_URL=${SHORTER_BASE_URL}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?schema=public
    networks:
      - url-shorter

  database:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - url-shorter

  migrations:
    build:
      context: .
      target: builder
    restart: on-failure
    command: npx prisma migrate dev
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?schema=public
    networks:
      - url-shorter
